name: Deploy to CI over SFTP
on:
    push:
        branches:
            -   main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'root'
        server: '159.89.171.253'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
        local_path: './*'
        remote_path: '/var/www/html/qa' #make sure dir exist
        args: '-o ConnectTimeout=5'
