name: Build and Deploy
on:
    push:
        branches:
            -   main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@master
            -   name: Setup Enviroment
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
            -   name: Install Packages
                run: composer install --no-dev
            -   name: Deploy to Server
                uses: ngocquyhoang/deploy@laravel
                with:
                    user: root
                    host: 159.89.171.253
                    path: /var/www/html/qa
                env:
                    DEPLOY_KEY: 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEAw+eZN8KJ/UnMKxk2yhb6koI5SuSiBFI7dNm/9SHCjwm6T4+0cY3IpMvw93PNyGwQp58ypEGy8LMo/TNbNjSTzb07viiu460iq2QAnRTlxLerqJIQaRYej6x2KcLTGM2Tkcjn24lgix7nHGGWy4d8nAGFMjNEGCrtJM/ETWsJfgyC18JtAECkf94Yu8BXFW1S7Ikni+V66ZDgvtVZNX/nazbpzdWPHVMjughIx5qwNE/ASREs+17cY8IfFXW3AksSbvqZyluuJKams/20C1ru+aqbF1/lCHht3oQA2dlL4wiGPdBwDUhV76qZW2lT226iSTn/IILBM41yMOTKzQOlAtkXqVVeMYIv48D4qVzvQJ30Uu2A0/ZoNWiwjraH52wVqdHywNT13GrHQfMyax6lqPBYzXDzOWJJCO9/KWz7LeZe+yyd7kNIhJNrcZaHj1KQzKo2de3NtEw8sG1MEoLvscW6RpN0hHfJYB0GreWkYW57MBPQKChrvWOcO5Ml4uGXAAAFgONQLjbjUC42AAAAB3NzaC1yc2EAAAGBAMPnmTfCif1JzCsZNsoW+pKCOUrkogRSO3TZv/Uhwo8Juk+PtHGNyKTL8PdzzchsEKefMqRBsvCzKP0zWzY0k829O74oruOtIqtkAJ0U5cS3q6iSEGkWHo+sdinC0xjNk5HI59uJYIse5xxhlsuHfJwBhTIzRBgq7STPxE1rCX4MgtfCbQBApH/eGLvAVxVtUuyJJ4vleumQ4L7VWTV/52s26c3Vjx1TI7oISMeasDRPwEkRLPte3GPCHxV1twJLEm76mcpbriSmprP9tAta7vmqmxdf5Qh4bd6EANnZS+MIhj3QcA1IVe+qmVtpU9tuokk5/yCCwTONcjDkys0DpQLZF6lVXjGCL+PA+Klc70Cd9FLtgNP2aDVosI62h+dsFanR8sDU9dxqx0HzMmsepajwWM1w8zliSQjvfyls+y3mXvssne5DSISTa3GWh49SkMyqNnXtzbRMPLBtTBKC77HFukaTdIR3yWAdBq3lpGFuezAT0Cgoa71jnDuTJeLhlwAAAAMBAAEAAAGBAIngvZBmBdJTlzOaGlqfU5m7t3EDexgJfDkgbB6ttQ4Q7aTDYl8tR9LcimrOgT2W+R3QSMccSkFoBug1tfNvi7sYfSy322b4Wtc/mcL0i0YpctJAgvZDEB1UZxG7QfFJ9pt7R9vWUzF2/XeXI5d5cvUliMYtGLbdt2vaIrHOLK8fRRNvjmHIHT61ZLj3hRLaj6tUWJX4W8p5IgSNiazCqXBnBKTOslwUQKfU3sxFDdCzdIS4Zu0/9WLspA3pfHVLuaFLgI4F/1YPcnNh/j0pdpGlYkoRvvzIkzC6KroIVnkuzIylisHYLPOf+1/MSGgl0gkfwD5ZBOJ0IjFiTYFk5FvIpf+QbftNHfGhnrPjGrTYTiROzoJf1MZAWkD85wXwNlwYU20eL5eY2LIH09qj5vnkPKdKkgEfzMY0RlMOW8nbxOmMLSCgUr+Jfe4Vo720K1H3bBUkZEeUrFBW3a2N2bcYQLNQPXN6Vgi6py/AKR42M26iv61L+qFFP7Rz+URAoQAAAMEAykTIKPK2KT9ahnS4KZQ1H/FXtgtcJ3ok5HUl8rDUeDCnuK0ydl9Jm6GjiaWTccnrXE54LJ2yI/k9an6jTp1We0EJRwck3Mcge3eyQllR6T0WCgGKiEEQQipkwO4jbcVtyqRWMqG5wVVvAH8A4b4d1RZWlDuvZ7JEX2GzPKkVBMU9b8XrXuSE36rdh7fRt+erUgX45UFH8qlOsIq6EFCT6BsVL/pIGuaOgiI1tQOaP2wWNt87abZtclXaZcBIltmFAAAAwQDikMzPqGndDQF3p9xhgHb14V7I+wenX0EAxLTgKqOZMQodBXZLZwvhWKlzLT0CirZ+zo54DCFQDc+Z1UolCI+ae7qlGaSjucjt2Zzt6hBl3dKihYpRuxmviM7P1ZGv+pCeAFJ/ZaAJMeVuDgekT4osV0tlUENWPpACTPvHuyOvzgpBBM+R3Kmmt16X3Jo8XPli2tJRCgEjPeHMd6+D3iAStce2KAJQa5HQefoW3rvQTOaE5pp9vHYp98bgTjB5hzEAAADBAN1bEOBx7x+myQvNbu0Px4OqwSyITVQAoI0yNyIqIky7WkwsFvLr4UxZR6w01Bq9zTzNubKB9lLoBiatvM9q+F2Y7yUWdUtRxEVVixa17fTp7gOQZvhZBuGfhQdZ/8OBXobKFgV+3yc+Rnak+vzB937HIz5clokzX+yMhUiSLG49onuZc9VyYoEPWmH3xIMS71UPQZ5/CLauQrVdcu3JbefstfnIqAkfyLJfE79UhEj2A59QoP0JkosdBB45p5HTRwAAAAdyb290QFFBAQI='
